includes= ideal,\
         creditcard,\
         reporting,\
         paypal,\
         alternative,\
         alipay,\
         applepay,\
         bancontact,\
         googlepay,\
         ideal,\
         klarna,\
         sofort,\
         wechatpay

uiTestSuites=isv.sap.payment.suite.category.b2c.WeChatPay,\
  isv.sap.payment.suite.category.b2c.CreditCardFlex,\
  isv.sap.payment.suite.category.b2c.CreditCardSOP,\
  isv.sap.payment.suite.category.b2c.CreditCardHOP,\
  isv.sap.payment.suite.category.b2c.PayPal,\
  isv.sap.payment.suite.category.b2c.GooglePay,\
  isv.sap.payment.suite.category.b2c.AliPay,\
  isv.sap.payment.suite.category.b2c.Ideal,\
  isv.sap.payment.suite.category.b2c.BanContact,\
  isv.sap.payment.suite.category.b2c.Klarna,\
  isv.sap.payment.suite.category.b2c.Sofort

#  isv.sap.payment.suite.category.b2b.CreditCardSOP,\
#  isv.sap.payment.suite.category.b2b.ReplenishmentCreditCardSOP,\
#  isv.sap.payment.suite.category.b2b.ReplenishmentCreditCardHOP,\
#  isv.sap.payment.suite.category.b2b.ReplenishmentAccount,\
#  isv.sap.payment.suite.category.b2b.Account,\
#  isv.sap.payment.suite.category.b2b.PayPal,\
#  isv.sap.payment.suite.category.b2b.CreditCardHOP
